Bench 397
AnswerConsulting/AnswerKing-CS pull request #109
Opened 2023-02-27 15:44 UTC by FoxHawk

Updated the POST & PUT requests for the Product endpoint to allow creating a product with tags & changing the tags a product has

2023-03-03 14:56 UTC, hazel-davis approved these changes, later dismissed

2023-03-06 09:42 UTC, bethcryer requested changes

2023-03-06 09:42 UTC, bethcryer commented on src/Answer.King.Api/Services/ProductService.cs
> +        var tags = await this.AssociateProductAndTags(product, createProduct.Tags);
I think this should be after `this.Tags.BeginTransaction();` so that it gets reverted if any of the associations fail

2023-03-06 09:42 UTC, bethcryer commented on src/Answer.King.Api/Services/ProductService.cs
> +        }
Don't think this loop is needed, `AssociateProductAndTags` will already throw errors if either of the entities are Retired

2023-03-06 10:43 UTC, bethcryer approved these changes

2023-03-07 10:13 UTC, CSL-Answer approved these changes
Looks good to me

2023-03-07 10:14 UTC, merged