BENCH-117: Change all Ids to int64/long
AnswerConsulting/AnswerKing-CS pull request #13
Opened 2022-11-08 09:16 UTC by bethcryer

2022-11-08 09:24 UTC, harrystead2 approved these changes, later dismissed

2022-11-08 09:25 UTC, milkshakeuk commented on src/Answer.King.Domain/Inventory/Category.cs
> -        this.Id = Guid.NewGuid();
not sure what to do here since guid's were guaranteed to be unique but longs aren't

2022-11-08 09:34 UTC, bethcryer commented on src/Answer.King.Domain/Inventory/Category.cs
> -        this.Id = Guid.NewGuid();
Setting it to 0 auto increments it in LiteDB so that's fine, but I did have to have some public constructors where you can manually set the Id too because a lot of the tests break without it.

2022-11-09 11:03 UTC, milkshakeuk requested changes
can you please review the comments.

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Orders/Order.cs
> +    public long Id { get; set; }
remove public setter.

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/ICategoryRepository.cs
> -    Task<Category?> GetByProductId(Guid productId);
bring this back :)

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public Category(long id, string name, string description)
is this right?

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public long Id { get; set; }
remove public setter.

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
>  public partial class Payment
is this meant to be partial?

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
> +    public Payment(long orderId, double amount, double orderTotal)
should `orderId` be in this constuctor?

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +    public long Id { get; set; }
remove public setter.

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/Repositories/Mappings/IEntityMapping.cs
> +    void RegisterMapping (BsonMapper mapper);
remove whitespace between method name and brackets... might wanna check the `.editorconfig` rules on this.

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/Repositories/Mappings/PaymentEntityMappings.cs
> +    public void ResolveMember (Type type, MemberInfo memberInfo, MemberMapper memberMapper)
remove whitespace between methodname and brackets, might be worth looking at `.editorconfig`

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/Repositories/Mappings/ProductEntityMappings.cs
> +    public void ResolveMember (Type type, MemberInfo memberInfo, MemberMapper memberMapper)
same here.

2022-11-09 11:03 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/SeedData/OrderData.cs
> +            new Order()
looks like I didnt push this change, can you put new order back to the top.

2022-11-09 11:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            ProductFactory.CreateProduct(1, "product 1", "desc", 2.0, category, false),
did you need to use the factory here?

2022-11-09 11:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            ProductFactory.CreateProduct(1, "product 1", "desc", 2.0, category, false),
same here.

2022-11-09 11:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        this.CategoryRepository.Get(product.Category.Id).Returns(oldCategory);
you might wanna change this back.

2022-11-09 11:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        this.CategoryRepository.Get(product.Category.Id).Returns(null as Category);
you might wanna change this back.

2022-11-09 11:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        this.CategoryRepository.Get(product.Category.Id)
you might wanna change this back.

2022-11-09 11:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        return CategoryFactory.CreateCategory(id, name, description, DateTime.UtcNow, DateTime.UtcNow, new List<Answer.King.Domain.Inventory.Models.ProductId>(), false);
do you 100% need the factories here?

2022-11-09 11:11 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            ProductFactory.CreateProduct(1, "product 1", "desc", 2.0, category, false),
It gives a 'Sequence contains more than one matching element' otherwise, I assume because both Ids are set to 0 without the Factory's constructor setting it manually

2022-11-09 11:16 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
> +    public Payment(long orderId, double amount, double orderTotal)
Believe so

2022-11-09 11:29 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public Category(long id, string name, string description)
think so, this one's used just for deserializing from the product so being able to directly set the id should be fine

2022-11-09 11:36 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        this.CategoryRepository.Get(product.Category.Id).Returns(oldCategory);
Done

2022-11-09 11:36 UTC, bethcryer commented on src/Answer.King.Infrastructure/SeedData/OrderData.cs
> +            new Order()
Done

2022-11-09 11:41 UTC, bethcryer commented on src/Answer.King.Infrastructure/Repositories/Mappings/PaymentEntityMappings.cs
> +    public void ResolveMember (Type type, MemberInfo memberInfo, MemberMapper memberMapper)
Done and changed .editorconfig

2022-11-09 13:53 UTC, bethcryer commented on src/Answer.King.Domain/Orders/Order.cs
> +    public long Id { get; set; }
Done, all the public Id setters are gone

2022-11-09 13:53 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/ICategoryRepository.cs
> -    Task<Category?> GetByProductId(Guid productId);
Done

2022-11-09 13:53 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
>  public partial class Payment
Doesn't seem like it, have removed and everything still works

2022-11-09 15:24 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        return CategoryFactory.CreateCategory(id, name, description, DateTime.UtcNow, DateTime.UtcNow, new List<Answer.King.Domain.Inventory.Models.ProductId>(), false);
I was able to get rid of one of the factory uses in this file, but the others are currently necessary. I *can* make a few more tests work without using factories by removing the Id default value guards from some entities, but the Ids passed to those *shouldn't* ever be 0 in production so that seems like a bad idea.

2022-11-09 15:25 UTC, bethcryer commented on src/Answer.King.Infrastructure/Repositories/Mappings/ProductEntityMappings.cs
> +    public void ResolveMember (Type type, MemberInfo memberInfo, MemberMapper memberMapper)
done

2022-11-09 15:25 UTC, bethcryer commented on src/Answer.King.Infrastructure/Repositories/Mappings/IEntityMapping.cs
> +    void RegisterMapping (BsonMapper mapper);
done

2022-11-09 15:48 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +    public long Id { get; set; }
done

2022-11-10 11:45 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            ProductFactory.CreateProduct(1, "product 1", "desc", 2.0, category, false),
CreateOrder and UpdateOrder both can't handle the Ids not being set to a non-zero value

2022-11-10 11:54 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
> +    public Payment(long orderId, double amount, double orderTotal)
It's only used in PaymentService, so we could replace that with the PaymentFactory creator or maybe add a method that sets the orderId and use that instead?

2022-11-10 16:12 UTC, milkshakeuk requested changes
can you review the comments please.

2022-11-10 16:12 UTC, milkshakeuk commented on .editorconfig
> +csharp_space_between_method_declaration_name_and_open_parenthesis = false
can you add the warning level to this i.e. `false:warninng`.

also add corresponding diagnostic rule for this..
```
# Fix formatting
dotnet_diagnostic.IDE0055.severity = warning
```

2022-11-10 16:12 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/ICategoryRepository.cs
> +    public Task<Category?> GetByProductId (long productId);
with an interface you dont need the `public` keyword.

2022-11-10 16:12 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public Category(long id, string name, string description)
was it public before? if so then no problem you can resolve the comment or let me know and ill resolve it.

2022-11-10 16:12 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
> +    public Payment(long orderId, double amount, double orderTotal)
if was there before then fine, let me know and ill resolve the comment.

2022-11-10 16:12 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        var product = ProductFactory.CreateProduct(1,
do we need the factory here? if so why wasnt it needed before?

2022-11-10 16:12 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        return CategoryFactory.CreateCategory(id, name, description, DateTime.UtcNow, DateTime.UtcNow, new List<Answer.King.Domain.Inventory.Models.ProductId>(), false);
as in do we still need the factories in the tests based on the other changes we have now made?

2022-11-10 16:12 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            ProductFactory.CreateProduct(1, "product 1", "desc", 2.0, category, false),
Can you check and let me know if you still need the factories here? it didn't seem to need them before.

2022-11-10 16:12 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/Extensions/DependencyInjection/LiteDbServiceCollectionExtensions.cs
> +            var originalResolver = BsonMapper.Global.ResolveMember;
can we move this line above the foreach.

2022-11-10 16:40 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        var product = ProductFactory.CreateProduct(1,
I could remove it if we get rid of the Id guard in ProductId. I think that might be safe to do actually - as far as I can tell ProductId is only used for deserializing from the database.

2022-11-10 16:44 UTC, bethcryer commented on .editorconfig
> +csharp_space_between_method_declaration_name_and_open_parenthesis = false
done

2022-11-10 16:45 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/ICategoryRepository.cs
> +    public Task<Category?> GetByProductId (long productId);
done

2022-11-10 16:45 UTC, bethcryer commented on src/Answer.King.Infrastructure/Extensions/DependencyInjection/LiteDbServiceCollectionExtensions.cs
> +            var originalResolver = BsonMapper.Global.ResolveMember;
gotcha

2022-11-11 10:22 UTC, milkshakeuk requested changes
last change I promise 😁

2022-11-11 10:22 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public Category(string name, string description)
this is a new constructor that didn't exist before... is it needed?

2022-11-11 10:25 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public Category(string name, string description)
oh you're right! I have no idea when or why I added that haha

2022-11-11 10:25 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Category.cs
> +    public Category(string name, string description)
It is now gone

2022-11-11 10:27 UTC, milkshakeuk approved these changes

2022-11-11 10:29 UTC, mbaltrimas approved these changes

2022-11-11 10:29 UTC, harrystead2 approved these changes

2022-11-11 10:30 UTC, merged