added integration tests for product
AnswerConsulting/AnswerKing-CS pull request #20
Opened 2022-11-15 10:03 UTC by kirbyAlasdairAnswer

2022-11-15 11:57 UTC, milkshakeuk requested changes
see comment.

2022-11-15 11:57 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var products = JsonConvert.DeserializeObject<IEnumerable<Product>>(result);
Have a look at using [ALBA](https://jasperfx.github.io/alba/) and [Verify](https://github.com/VerifyTests/Verify) to make this easier, then you wont need your custom Product class at all.

2022-11-15 11:59 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var products = JsonConvert.DeserializeObject<IEnumerable<Product>>(result);
https://jasperfx.github.io/alba/guide/hosting.html#initializing-albahost-with-webapplicationfactory

2022-11-15 13:35 UTC, hazel-davis commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var response = await this._httpClient.GetAsync("/api/products/5000");
it might be better to target something like "api/products/0" so that you can be certain there will be no product with that id

2022-11-15 13:37 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var response = await this._httpClient.GetAsync("/api/products/5000");
you can should you wish create a new DB file per test suite, you would just have to edit the connection string when building the WebApplication.

Then you know the data will be isolated per suite.

2022-11-15 13:38 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var response = await this._httpClient.GetAsync("/api/products/5000");
you can should you wish create a new DB file per test suite, you would just have to edit the connection string when building the webapplication.

Then you know the data will be isolated per suite.

If we were ever to decide to move to a SQL based persistence mechanism we could use:
https://github.com/jbogard/Respawn

2022-11-15 15:14 UTC, kirbyAlasdairAnswer commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var response = await this._httpClient.GetAsync("/api/products/5000");
we are making a new instance of the db for the test run (that is cleaned up after), this lets us call a valid endpoint and check that no resource exists there

2022-11-15 15:40 UTC, milkshakeuk requested changes
couple of coments

2022-11-15 15:40 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Common/WebFixtures.cs
> +        string path = Directory.GetCurrentDirectory();
you don't seem to be using the path here.

2022-11-15 15:40 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.PutProduct_InvalidId_ReturnsNotFound.verified.txt
> +  traceId: 00-ac91cf7619c96ae79753db5d73ad302b-831682f4b119803e-00
got a feeling these traceids might trip you up since they are unique every time I think, there is a way with Verify to tell it to ignore these in a similar way datetime types work.

2022-11-15 15:40 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +[UsesVerify]
carriage return after namespace?

2022-11-15 15:40 UTC, milkshakeuk commented on tests/Answer.King.Test.Common/Answer.King.Test.Common.csproj
> +    <ProjectReference Include="..\..\src\Answer.King.Domain\Answer.King.Domain.csproj" />
you shouldnt reference this project in the `Tests.Common` project

2022-11-16 09:15 UTC, milkshakeuk requested changes
can you check these comments please.

2022-11-16 09:15 UTC, milkshakeuk commented on src/Answer.King.Api/Program.cs
> +public partial class Program { }
I checked out your branch and removed this line, it didn't see, to be needed.

2022-11-16 09:15 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Common/WebFixtures.cs
> +namespace Answer.King.Api.IntegrationTests.Common;
do we not need a carriage return after the namespace? same in other files.

2022-11-16 09:15 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var putResult = await this._host.Scenario(_ =>
`putResult` isn't being used.

2022-11-16 09:15 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Controllers/ProductControllerTests.cs
> +        var deleteResult = await this._host.Scenario(_ =>
`deleteResult` isn't being used.

2022-11-16 09:28 UTC, kirbyAlasdairAnswer commented on src/Answer.King.Api/Program.cs
> +public partial class Program { }
im guessing updating to alba made this uneccessary

2022-11-16 10:47 UTC, milkshakeuk commented on src/Answer.King.Api/Program.cs
> +public partial class Program { }
ah yeah possibly

2022-11-16 11:20 UTC, milkshakeuk approved these changes
looks good

2022-11-16 11:26 UTC, hazel-davis approved these changes

2022-11-16 11:27 UTC, merged