Bench 118
AnswerConsulting/AnswerKing-CS pull request #23
Opened 2022-11-18 11:10 UTC by CallumMcGregorAD

2022-11-18 11:52 UTC, kirbyAlasdairAnswer reviewed
few styling points, can you also squash all those commits please

2022-11-18 11:52 UTC, kirbyAlasdairAnswer commented on src/Answer.King.Domain/Inventory/Models/Category.cs
> +﻿namespace Answer.King.Domain.Inventory.Models;
any reason this is being moved down a level?

2022-11-18 11:52 UTC, kirbyAlasdairAnswer commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +        var exists = this._Categories.Any(p => p.Id == category.Id);
i think this could be a bit more space efficient, if (this._Categories.Any(p => p.Id == category.Id)) => add categories

2022-11-18 11:52 UTC, kirbyAlasdairAnswer commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +        var existing = this._Categories.SingleOrDefault(p => p.Id == categoryId);
same here

2022-11-18 13:54 UTC, CallumMcGregorAD commented on src/Answer.King.Domain/Inventory/Models/Category.cs
> +﻿namespace Answer.King.Domain.Inventory.Models;
It was outside of the models folder, I assumed it should be in there

2022-11-18 15:51 UTC, kirbyAlasdairAnswer commented on src/Answer.King.Domain/Inventory/Models/Category.cs
> +﻿namespace Answer.King.Domain.Inventory.Models;
i think the way Jake was doing it was that this was a dependant class so Category which uses a model Product, same way Order then uses models Category/Line Item/Product

2022-11-18 16:13 UTC, CallumMcGregorAD commented on src/Answer.King.Domain/Inventory/Models/Category.cs
> +﻿namespace Answer.King.Domain.Inventory.Models;
I understand, I'll change it back.

2022-11-21 10:31 UTC, kirbyAlasdairAnswer approved these changes, later dismissed

2022-11-21 10:36 UTC, milkshakeuk requested changes
Just a few comments

2022-11-21 10:36 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ProductService.cs
> +            else
to reduce nesting, you can get rid of the else and use the continue keyword ...
```csharp
foreach (var oldCategory in oldCategories.ToList())
{
    // If old category is not still present in updated list, remove link between product and category.
    if (!updateIds.Contains(oldCategory.Id))
    {
        oldCategory.RemoveProduct(new Domain.Inventory.Models.ProductId(productId));
        await this.Categories.Save(oldCategory);

        product.RemoveCategory(oldCategory.Id);
        continue;
    }

    // Else check that the category is still in the database.
    var category = await this.Categories.Get(oldCategory.Id);

    if (category == null)
    {
        throw new ProductServiceException("The provided category id is not valid.");
    }

    category.AddProduct(new Domain.Inventory.Models.ProductId(productId));
    await this.Categories.Save(category);

    product.AddCategory(new Category(category.Id, category.Name, category.Description));

    updateIds.Remove(oldCategory.Id);
}
```

2022-11-21 10:36 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ProductService.cs
> +            if (category != null)
I don't think the null check is required here since it should never get into that state, i.e. array of null? if it has there is an issue somewhere else.

2022-11-21 10:36 UTC, milkshakeuk commented on src/Answer.King.Domain/Inventory/Category.cs
> +    public Category(string name, string description, IList<ProductId> products)
should we be passing products into this constructor? we never used to pass a single one for example.

2022-11-21 10:36 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +        if (!this._Categories.Any(p => p.Id == category.Id))
if you want the ids to be unique you could use a `HashSet<T>` then you don't need to check that it isn't already in the set.

2022-11-21 10:36 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +        var existing = this._Categories.SingleOrDefault(p => p.Id == categoryId);
same here if you use a `HashSet<T>` you don't need to check if it exists.

2022-11-21 10:36 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Common/Models/Product.cs
> +        //Guard.AgainstNullArgument(nameof(categories), categories);
`Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);`

2022-11-21 15:29 UTC, milkshakeuk requested changes
2 small changes.

2022-11-21 15:29 UTC, milkshakeuk commented on src/Answer.King.Domain/Orders/Models/Product.cs
> +        Guard.AgainstNullArgument(nameof(categories), categories);
`Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);`

2022-11-21 15:29 UTC, milkshakeuk commented on src/Answer.King.Api/RequestModels/ProductDto.cs
> +    public List<CategoryId> Categories { get; init; } = null!;
`public List<CategoryId> Categories { get; init; } = new List<CategoryId>();`

2022-11-21 15:35 UTC, milkshakeuk approved these changes

2022-11-21 15:45 UTC, harrystead2 approved these changes

2022-11-21 15:47 UTC, SWhyteAnswer approved these changes

2022-11-21 15:48 UTC, merged