Bench 142 - Add Integration Tests for Order Controller
AnswerConsulting/AnswerKing-CS pull request #30
Opened 2022-11-23 15:28 UTC by hazel-davis

Integration tests for order endpoints.
I've also scrubbed Id values from all verify snapshots to let the tests be run in any order/combination

2022-11-24 08:32 UTC, kirbyAlasdairAnswer reviewed
looks good, just something weird going on with the verified/recieved.txt for product

2022-11-24 08:32 UTC, kirbyAlasdairAnswer commented on tests/Answer.King.Api.IntegrationTests/Controllers/OrderControllerTests.cs
> +        return await Verify(orders, this._errorLevelSettings);
bit of a nitpick but if we are applying this scrubber pattern to all responses not just errors lets rename it to show that

2022-11-24 08:32 UTC, kirbyAlasdairAnswer commented on tests/Answer.King.Api.IntegrationTests/Controllers/OrderControllerTests.RetireProduct_ValidId_IsRetired_ReturnsNotFound.verified.txt
> +  status: 410,
why does this and almost every other product test verified.txt now live under the OrderControllerTests domain?

2022-11-24 08:32 UTC, kirbyAlasdairAnswer commented on tests/Answer.King.Api.IntegrationTests/Controllers/OrderControllerTests.GetProducts_ReturnsList.verified.txt
> +﻿[
whats happened here? this is a product test returning an empty order object?

2022-11-24 08:32 UTC, kirbyAlasdairAnswer commented on tests/Answer.King.Api.IntegrationTests/Controllers/OrderControllerTests.PostOrder_ValidModel_ReturnsNewOrder.verified.txt
> +            Id: {Scrubbed},
not an issue with your pr, but should this not be returning categories id only? like for get product

2022-11-24 12:05 UTC, hazel-davis commented on tests/Answer.King.Api.IntegrationTests/Controllers/OrderControllerTests.PostOrder_ValidModel_ReturnsNewOrder.verified.txt
> +            Id: {Scrubbed},
That's what it is on the API contract, each category with an array of products that have an array of ids.

2022-11-24 12:06 UTC, hazel-davis commented on tests/Answer.King.Api.IntegrationTests/Controllers/OrderControllerTests.RetireProduct_ValidId_IsRetired_ReturnsNotFound.verified.txt
> +  status: 410,
This (and some weird empty snapshots) are an artifact of playing around with the test domains, should be removed now.

2022-11-25 10:02 UTC, milkshakeuk requested changes
couple of changes.

2022-11-25 10:02 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Answer.King.Api.IntegrationTests.csproj
> +  <ItemGroup>
all these needs removing.

2022-11-25 10:02 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Common/WebFixtures.cs
> +    public readonly string TestDbName = $"Answer.King.{Guid.NewGuid()}.db";
this needs to be made private again.

2022-11-25 11:17 UTC, milkshakeuk submitted a review, later dismissed

2022-11-25 11:17 UTC, milkshakeuk commented
@hazel-davis can you rebase please 😊

2022-11-25 11:24 UTC, kirbyAlasdairAnswer submitted a review, later dismissed

2022-11-25 11:57 UTC, hazel-davis commented
hold on I've broken something

2022-11-25 12:44 UTC, kirbyAlasdairAnswer approved these changes

2022-11-25 12:44 UTC, milkshakeuk approved these changes

2022-11-25 12:48 UTC, merged