BENCH-143: Update Add Category to Product
AnswerConsulting/AnswerKing-CS pull request #31
Opened 2022-11-24 09:02 UTC by bethcryer

You can now update the collection of products in each category through the Category POST and PUT endpoints.
You can no longer do so through the Product POST and PUT endpoints.

Tests have been updated, and I moved some over from ProductServiceTests to CategoryServiceTests since they're now applicable there instead.

2022-11-24 09:37 UTC, milkshakeuk commented on src/Answer.King.Api/Validators/CategoryValidator.cs
> +        this.RuleFor(p => p.Products)
We probably want a `.NotEmpty()` before the `.ForEach`

2022-11-24 09:38 UTC, milkshakeuk commented on src/Answer.King.Domain/Inventory/Category.cs
>          Guard.AgainstNullOrEmptyArgument(nameof(description), description);
We need to guard against null for products here.

2022-11-24 09:40 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> -        Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);
do we at least need a guard for null for categories? I think we do.

2022-11-24 10:32 UTC, bethcryer commented on src/Answer.King.Api/Validators/CategoryValidator.cs
> +        this.RuleFor(p => p.Products)
Do we always want new Categories to contain at least one product?

2022-11-24 10:41 UTC, bethcryer commented on src/Answer.King.Domain/Inventory/Category.cs
>          Guard.AgainstNullOrEmptyArgument(nameof(description), description);
done

2022-11-24 10:41 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> -        Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);
yup added it back in

2022-11-25 10:04 UTC, milkshakeuk commented on src/Answer.King.Api/Validators/CategoryValidator.cs
> +        this.RuleFor(p => p.Products)
good point probably not.

2022-11-25 10:21 UTC, milkshakeuk requested changes
couple of comments.

2022-11-25 10:21 UTC, milkshakeuk commented on src/Answer.King.Api/Services/CategoryService.cs
> +
extra carriage return needs removing.

2022-11-25 10:21 UTC, milkshakeuk commented on src/Answer.King.Domain/Orders/Models/Product.cs
> -        Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);
I think we need to guard against null categories here.

2022-11-25 10:21 UTC, milkshakeuk commented on tests/Answer.King.Api.IntegrationTests/Common/Models/Product.cs
> -        Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);
do we even need any guards in the integration tests models?

2022-11-25 10:40 UTC, bethcryer commented on tests/Answer.King.Api.IntegrationTests/Common/Models/Product.cs
> -        Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);
good shout, have now removed those guards and also the setters that weren't being used

2022-11-25 10:40 UTC, bethcryer commented on src/Answer.King.Domain/Orders/Models/Product.cs
> -        Guard.AgainstNullOrEmptyArgument(nameof(categories), categories);
done

2022-11-25 10:40 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +
done

2022-11-25 10:53 UTC, milkshakeuk approved these changes

2022-11-25 10:54 UTC, kirbyAlasdairAnswer approved these changes

2022-11-25 10:59 UTC, merged