Draft: Bench-234: Sonarcloud fixes
AnswerConsulting/AnswerKing-CS pull request #34
Opened 2022-11-28 16:51 UTC by hazel-davis

2022-11-29 09:51 UTC, hazel-davis commented
Code smells [here](https://sonarcloud.io/project/issues?resolved=false&types=CODE_SMELL&sinceLeakPeriod=true&branch=BENCH-234&id=AnswerKing)

2022-11-29 12:44 UTC, bethcryer requested changes

2022-11-29 12:44 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +// ReSharper disable once UnusedMember.Local
Think you ought to move this to the line above the private constructor you're trying to ignore

2022-11-29 12:44 UTC, bethcryer commented on src/Answer.King.Api/Common/Validators/CamelCasePropertyNameResolver.cs
> +// ReSharper disable once UnusedMember.Local
This can also move to above the private method

2022-11-29 12:44 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/Models/Payment.cs
> +// ReSharper disable once UnusedMember.Local
Move this

2022-12-01 11:04 UTC, bethcryer approved these changes

2022-12-02 11:19 UTC, merged