BENCH-274: Add the Tag entity and endpoints
AnswerConsulting/AnswerKing-CS pull request #47
Opened 2023-01-03 09:31 UTC by bethcryer

2023-01-03 12:32 UTC, harrystead2 approved these changes, later dismissed

2023-01-04 09:57 UTC, milkshakeuk requested changes
just a few changes.

2023-01-04 09:57 UTC, milkshakeuk commented on src/Answer.King.Api/Controllers/TagsController.cs
> +    [SwaggerOperation(Tags = new[] { "Tags" })]
You don't explicitly need the Attribute here since it will auto tag them with the controller's name. i.e. `{Tags}Controller`.

Same with all the actions on this controller.

2023-01-04 09:57 UTC, milkshakeuk commented on src/Answer.King.Api/Services/Extensions/OrderExtensions.cs
>      {
does the order care about tags? isn't that just an inventory thing?

2023-01-04 09:57 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/Repositories/Mappings/CategoryFactory.cs
> +    private static ConstructorInfo? CategoryConstructor
don't do it this way as it will execute this code every time the propery is acccessed, it needs to be the same as described yesterday on slack i.e. 

```
private static ConstructorInfo? CategoryConstructor { get; } = typeof(Category)
            .GetConstructors(BindingFlags.Instance | BindingFlags.NonPublic)
            .SingleOrDefault(c => c.IsPrivate && c.GetParameters().Length > 0);
```

Same for the others too.

2023-01-04 14:04 UTC, bethcryer commented on src/Answer.King.Api/Services/Extensions/OrderExtensions.cs
>      {
Think you might be right - I believe the categories don't need to be returned as part of an order either, so I can remove that too

2023-01-05 08:51 UTC, milkshakeuk requested changes
Few more comments.

2023-01-05 08:51 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +    public async void Post_ValidRequestCallsGetAction_ReturnsNewCategory()
Avoid async void... its [bad practice](https://learn.microsoft.com/en-us/archive/msdn-magazine/2013/march/async-await-best-practices-in-asynchronous-programming#avoid-async-void).

Do async Task instead.

2023-01-05 08:51 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/TagsControllerTests.cs
> +    public async void GetAll_ValidRequest_ReturnsOkObjectResult()
same here.

2023-01-05 08:51 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/CategoryServiceTests.cs
> +    public async void RetireCategory_AlreadyRetired_ThrowsException()
same here.

2023-01-05 08:51 UTC, milkshakeuk commented on src/Answer.King.Domain/Orders/Order.cs
> +    public void AddLineItem(long productId, string productName, string productDescription, double price, int quantity = 1)
this might come back to bite us, what does the API contract say? even if we remove it from here technically, we can still hydrate it in the service but it won't be a point in time snapshot for the Category & Tags not sure if that's a bad thing or not.

2023-01-10 08:55 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +    private HashSet<TagId> _Tags { get; }
shouldn't this be `_tags` ?

2023-01-10 09:04 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +    public async void Post_ValidRequestCallsGetAction_ReturnsNewCategory()
async void?

2023-01-10 09:04 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +    public async void Put_ProductIdNotValid_ReturnsValidationProblem()
async void.

2023-01-10 10:12 UTC, milkshakeuk commented on src/Answer.King.Domain/Repositories/Models/Product.cs
> +        this._categories.Add(category);
shouldn't there be a new line between the brace and this line?

2023-01-10 10:33 UTC, DWatson1993 commented on src/Answer.King.Api/Controllers/TagsController.cs
> +[Route("api/[controller]")]
Does this need to be [Route("api/tags")] ?
I know it's the same with all the other Controller files but was something I was picked up on during the Academy

2023-01-10 10:33 UTC, DWatson1993 commented on src/Answer.King.Api/Controllers/TagsController.cs
> +    /// <returns></returns>
Could the <returns></returns> be removed as they aren't being used?

2023-01-10 10:33 UTC, DWatson1993 commented on src/Answer.King.Api/Controllers/TagsController.cs
> +    /// <returns></returns>
Could this be removed?

2023-01-10 10:33 UTC, DWatson1993 commented on src/Answer.King.Api/Services/ITagService.cs
> +    Task<Tag> CreateTag(RequestModels.Tag createTag);
Would this benefit from having summaries added to them or is the controller file summaries enough to cover this?

2023-01-10 10:33 UTC, DWatson1993 commented on src/Answer.King.Domain/Repositories/ITagRepository.cs
> +{
Is there something missing from here?

2023-01-10 10:33 UTC, DWatson1993 commented on tests/Answer.King.Api.UnitTests/Common/CustomConverters/CategoryIdJsonConverterTests.cs
> +        var tagIdJsonConverter = new CategoryIdJsonConverter();
Is this the correct variable name?

2023-01-10 10:33 UTC, DWatson1993 commented on tests/Answer.King.Api.UnitTests/Common/CustomConverters/ProductIdJsonConverterTests.cs
> +        var tagIdJsonConverter = new ProductIdJsonConverter();
variable name correct?

2023-01-10 10:33 UTC, DWatson1993 commented on tests/Answer.King.Api.UnitTests/Common/CustomConverters/TagIdJsonConverterTests.cs
> +        var tagIdJsonConverter = new TagIdJsonConverter();
variable name correct?

2023-01-10 10:43 UTC, bethcryer commented on src/Answer.King.Api/Services/ITagService.cs
> +    Task<Tag> CreateTag(RequestModels.Tag createTag);
Don't think these need summaries no, those are just for generating the swagger documentation on the controllers

2023-01-10 10:46 UTC, bethcryer commented on src/Answer.King.Domain/Repositories/ITagRepository.cs
> +{
Nah this is just implementing IAggregateRepository<Tag> - I suppose we could do that directly in TagRepository, but having its own interface just makes things a bit clearer for reading

2023-01-10 10:48 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Common/CustomConverters/TagIdJsonConverterTests.cs
> +        var tagIdJsonConverter = new TagIdJsonConverter();
this one is :P

2023-01-10 11:06 UTC, bethcryer commented on src/Answer.King.Api/Controllers/TagsController.cs
> +[Route("api/[controller]")]
Either way is fine really, I think we'll leave it as is unless there's a compelling reason to change

2023-01-10 11:48 UTC, DWatson1993 commented on tests/Answer.King.Api.UnitTests/Common/CustomConverters/CategoryIdJsonConverterTests.cs
> +        // Act / Assert
Needs changing to // Assert

2023-01-10 11:53 UTC, DWatson1993 commented on tests/Answer.King.Api.UnitTests/Common/CustomConverters/ProductIdJsonConverterTests.cs
> +        // Act / Assert
Just assert

2023-01-10 13:34 UTC, DWatson1993 commented on tests/Answer.King.Infrastructure.UnitTests/Repositories/Factories/PaymentFactoryTests.cs
> +    private static readonly PaymentFactory paymentFactory = new();
Does this need to be caps like the others? I think in Product and Tags tests

2023-01-10 13:38 UTC, DWatson1993 commented on tests/Answer.King.Infrastructure.UnitTests/Repositories/Factories/ProductFactoryTests.cs
> +    private static readonly ProductFactory productFactory = new();
Caps like the others?

2023-01-10 13:40 UTC, DWatson1993 commented on tests/Answer.King.Infrastructure.UnitTests/Repositories/Factories/TagFactoryTests.cs
> +    private static readonly TagFactory tagFactory = new();
Caps like the others?

2023-01-10 13:55 UTC, DWatson1993 approved these changes

2023-01-10 14:22 UTC, milkshakeuk commented on tests/Answer.King.Infrastructure.UnitTests/Repositories/Factories/PaymentFactoryTests.cs
> +    private static readonly PaymentFactory paymentFactory = new();
these will change with the next PR which brings in style cop instead of rolsynator

2023-01-10 14:22 UTC, milkshakeuk commented on tests/Answer.King.Infrastructure.UnitTests/Repositories/Factories/ProductFactoryTests.cs
> +    private static readonly ProductFactory productFactory = new();
these will change with the next PR which brings in style cop instead of rolsynator

2023-01-10 14:22 UTC, milkshakeuk commented on tests/Answer.King.Infrastructure.UnitTests/Repositories/Factories/TagFactoryTests.cs
> +    private static readonly TagFactory tagFactory = new();
these will change with the next PR which brings in style cop instead of rolsynator

2023-01-10 14:26 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ITagService.cs
> +    Task<Tag> CreateTag(RequestModels.Tag createTag);
sometimes it's useful to add xml docs but in this case I'm not sure., since it's quite simple and easy to tell what it does.

If you needed to generate some documentation then it might be a good idea to add some basic info here.

2023-01-10 14:30 UTC, milkshakeuk approved these changes

2023-01-10 14:59 UTC, hazel-davis approved these changes

2023-01-10 15:00 UTC, merged