BENCH-275: Change Product to Hold a Category Instead of a List
AnswerConsulting/AnswerKing-CS pull request #48
Opened 2023-01-04 13:04 UTC by harrystead2

2023-01-05 11:23 UTC, milkshakeuk requested changes
Left some comments.

2023-01-05 11:23 UTC, milkshakeuk commented on src/Answer.King.Api/Extensions/DependencyInjection/SwaggerGenOptionsExtensions.cs
> +                schemaId = $"Repositories.{schemaId}.Response";
why did you change this?

2023-01-05 11:23 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            new Product("product 1", "desc", 2.0, new Domain.Repositories.Models.Category(1, "name", "description")),
does this need to be fully qualified?

2023-01-05 11:23 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +            "product", "desc", 12.00, new Domain.Repositories.Models.Category(1, "category", "desc"), false);
Does this need to be fully qualified?

2023-01-05 14:26 UTC, harrystead2 commented on src/Answer.King.Api/Extensions/DependencyInjection/SwaggerGenOptionsExtensions.cs
> +                schemaId = $"Repositories.{schemaId}.Response";
Swagger was throwing an error saying that there were two identical schemeIds. We had two SchemaIds referencing Inventory

2023-01-05 14:27 UTC, harrystead2 commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            new Product("product 1", "desc", 2.0, new Domain.Repositories.Models.Category(1, "name", "description")),
It seems it does

2023-01-06 16:51 UTC, hazel-davis commented on src/Answer.King.Api/Services/ProductService.cs
> +            new Category(category.Id, category.Name, category.Description));
Shouldn't UpdateProduct also have this feature added? Currently PUT api/product/{id} accepts a category Id in the body but ignores it in the service layer.

2023-01-12 08:42 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            new Product("product 1", "desc", 2.0, new Domain.Repositories.Models.Category(1, "name", "description")),
hmmm that doesn't make sense.

2023-01-12 08:42 UTC, milkshakeuk commented on src/Answer.King.Api/Extensions/DependencyInjection/SwaggerGenOptionsExtensions.cs
> +                schemaId = $"Repositories.{schemaId}.Response";
we should probably have a look at that.

2023-01-12 08:43 UTC, milkshakeuk commented
@harrystead2 this needs rebasing and any conflicts need fixing.

2023-01-13 09:32 UTC, bethcryer commented on src/Answer.King.Api/Services/ProductService.cs
> +            new Category(category.Id, category.Name, category.Description));
The functionality is now included in PUT too

2023-01-13 11:32 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            new Product("product 1", "desc", 2.0, new Domain.Repositories.Models.Category(1, "name", "description")),
can we not add a using alias at the top the same as Order, Product and TagId?

2023-01-13 11:51 UTC, FoxHawk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            new Product("product 1", "desc", 2.0, new Domain.Repositories.Models.Category(1, "name", "description")),
Had a quick look at this and there isn't a using statement for `Domain.Repositories.Models` which might be why it has to be fully qualified? But adding the using statement would cause a conflict with `Answer.King.Api.RequestModels.Category`.

2023-01-17 14:44 UTC, milkshakeuk requested changes

2023-01-17 14:44 UTC, milkshakeuk commented on src/Answer.King.Api/Common/JsonConverters/CategoryIdJsonConverter.cs
> +        writer.WriteNumberValue(value.Id);
Can you change the name of the property back to Value.

2023-01-17 14:44 UTC, milkshakeuk commented on src/Answer.King.Api/RequestModels/CategoryId.cs
> +    public long Id { get; init; }
`Value`

2023-01-17 14:44 UTC, milkshakeuk commented on src/Answer.King.Api/RequestModels/Product.cs
> +    public CategoryId Category { get; set; } = null!;
the property should be called `CategoryId`.

2023-01-17 14:44 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ProductService.cs
> +        var category = await this.Categories.GetOne(createProduct.Category.Id);
this `CategoryId` property should have an implicit conversion to long meaning you only need to pass `CategoryId` into the `GetOne` call.

2023-01-17 14:44 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ProductService.cs
> +        if (product.Category.Id != updateProduct.Category.Id)
```csharp
if (product.Category.Id != updateProduct.CategoryId) // implicit conversion.
```

2023-01-17 14:44 UTC, milkshakeuk commented on tests/Answer.King.Infrastructure.UnitTests/Answer.King.Infrastructure.UnitTests.csproj
> +    <ProjectReference Include="..\..\src\Answer.King.Api\Answer.King.Api.csproj" />
do you need to reference this project? I suspect not!

2023-01-17 15:56 UTC, FoxHawk commented on tests/Answer.King.Infrastructure.UnitTests/Answer.King.Infrastructure.UnitTests.csproj
> +    <ProjectReference Include="..\..\src\Answer.King.Api\Answer.King.Api.csproj" />
This is for `Infrastructure.UnitTests.Repositories.Models.CategoryTests` as it needs access to the CategoryId for it's test which is now in the api project

2023-01-18 10:42 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ProductService.cs
> +            throw new ProductServiceException("The provided category is not valid.");
`"The provided product category Id is not valid."

2023-01-18 10:45 UTC, milkshakeuk commented on src/Answer.King.Api/OpenApi/ProductCategorySchemaFilter.cs
> +            schema.Properties["category"].Items = schema.Properties["id"];
I believe this should be `categoryId`
```csharp
schema. Properties["categoryId"].Items = schema. Properties["id"];
schema. Properties["categoryId"].Nullable = false;
```

2023-01-18 10:49 UTC, milkshakeuk commented on src/Answer.King.Api/Services/ProductService.cs
> +            var category = await this.Categories.GetOne(updateProduct.CategoryId.Value);
this should be implicit.

```csharp
var category = await this.Categories.GetOne(updateProduct.CategoryId);
```

2023-01-18 10:55 UTC, milkshakeuk commented on src/Answer.King.Api/RequestModels/CategoryId.cs
> +using Answer.King.Domain;
why is this using needed? is it because of the Guard? if so just resolve this.

2023-01-18 10:57 UTC, FoxHawk commented on src/Answer.King.Api/RequestModels/CategoryId.cs
> +using Answer.King.Domain;
Yep it's for the Guard

2023-01-18 11:02 UTC, FoxHawk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +            new Product("product 1", "desc", 2.0, new Domain.Repositories.Models.Category(1, "name", "description")),
Renamed `Domain.Repositories.Models.Category` to `ProductCategory` which removes the need for this to be fully qualified

2023-01-18 12:41 UTC, FoxHawk commented on src/Answer.King.Api/OpenApi/ProductCategorySchemaFilter.cs
> +            schema.Properties["category"].Items = schema.Properties["id"];
This change produces the following error from swagger:
![image](https://user-images.githubusercontent.com/95636478/213174008-6a6bb9ef-57e9-4d96-a578-7ef3a4d15280.png)

2023-01-18 14:42 UTC, bethcryer commented on src/Answer.King.Api/OpenApi/ProductCategorySchemaFilter.cs
> +            schema.Properties["category"].Items = schema.Properties["id"];
Think the original is right, this is referencing the ProductCategory in Product, not a category id

2023-01-18 14:54 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +        var categoryRequestModel = new Api.RequestModels.Category
Does this need the Api qualification? it shouldn't do.

2023-01-18 14:56 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/TagsControllerTests.cs
> +        var tagRequestModel = new Api.RequestModels.Tag
same here... are we missing a using statement?

2023-01-18 14:56 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/CategoryServiceTests.cs
> +        var categoryRequest = new Api.RequestModels.Category
same here.

2023-01-18 14:57 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/OrderServiceTests.cs
> +        var orderRequest = new Api.RequestModels.Order
again here?

2023-01-18 14:57 UTC, FoxHawk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +        var categoryRequestModel = new Api.RequestModels.Category
It conflicts with the new namespace for the test that I moved over (`Api.UnitTests.RequestModels`)

2023-01-18 14:57 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/ProductServiceTests.cs
> +        var request = new Api.RequestModels.Product
again here.

2023-01-18 14:57 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Services/TagServiceTests.cs
> +        var tagRequest = new Api.RequestModels.Tag
again here.

2023-01-18 15:00 UTC, milkshakeuk commented on src/Answer.King.Api/OpenApi/ProductCategorySchemaFilter.cs
> +            schema.Properties["category"].Items = schema.Properties["id"];
ah okay fair enough, change it back to how you originally did it then.

2023-01-18 15:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +        var categoryRequestModel = new Api.RequestModels.Category
not sure how? the request model namespace is `Answer.King.Api.RequestModels` not `Answer.King.Api.UnitTests.RequestModels` unless there is a Category class in both locations somehow?

2023-01-18 15:07 UTC, FoxHawk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> +        var categoryRequestModel = new Api.RequestModels.Category
There isn't but without adding the `APi.` it gives the following error message: `The type or namespace name 'Category' does not exist in the namespace 'Answer.King.Api.UnitTests.RequestModels'` which is the conflict I was talking about

2023-01-18 15:13 UTC, FoxHawk commented on src/Answer.King.Api/OpenApi/ProductCategorySchemaFilter.cs
> +            schema.Properties["category"].Items = schema.Properties["id"];
I believe those fields are already showing in swagger

2023-01-20 12:50 UTC, FoxHawk commented on src/Answer.King.Api/OpenApi/ProductCategorySchemaFilter.cs
> +            schema.Properties["category"].Items = schema.Properties["id"];
Just fyi, I didn't push this change so it's still `"category"`

2023-01-20 13:46 UTC, bethcryer submitted a review, later dismissed

2023-01-20 14:22 UTC, milkshakeuk submitted a review, later dismissed

2023-01-23 16:05 UTC, milkshakeuk commented
@FoxHawk @bethcryer I think this can be rebased now.

2023-01-23 16:11 UTC, bethcryer approved these changes

2023-01-24 09:01 UTC, milkshakeuk approved these changes

2023-01-24 09:03 UTC, merged