BENCH 281 - Create Order Controller unit tests
AnswerConsulting/AnswerKing-CS pull request #50
Opened 2023-01-11 13:05 UTC by hazel-davis

2023-01-12 08:47 UTC, milkshakeuk commented
branch needs rebasing I think and conflicts resolving.

2023-01-13 09:36 UTC, bethcryer requested changes

2023-01-13 09:36 UTC, bethcryer commented on tests/Answer.King.Api.UnitTests/Controllers/OrdersControllerTests.cs
> +    public async void GetAll_ValidRequest_ReturnsOkObjectResult()
Any `async void` test methods need to be changed to `async Task`

2023-01-13 10:03 UTC, milkshakeuk requested changes

2023-01-13 10:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/CategoriesControllerTests.cs
> -[TestCategory(TestType.Unit)]
Any reason you have removed this?

2023-01-13 10:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/OrdersControllerTests.cs
>  public class OrdersControllerTests
No Test Category?

2023-01-13 10:03 UTC, milkshakeuk commented on tests/Answer.King.Api.UnitTests/Controllers/OrdersControllerTests.cs
> +            nameof(OrdersController.GetOne), "{id:long}");
you should remove the type hint here as it changes the behaviour of the endpoints.
https://learn.microsoft.com/en-us/aspnet/core/mvc/controllers/routing?view=aspnetcore-7.0#attribute-routing-with-http-verb-attributes

2023-01-13 14:32 UTC, bethcryer approved these changes

2023-01-13 16:01 UTC, milkshakeuk approved these changes

2023-01-13 16:02 UTC, merged