Trigger docker pull for new image
AnswerConsulting/AnswerKing-CS pull request #77
Opened 2023-01-26 13:40 UTC by CallumMcGregorAD

2023-01-26 13:56 UTC, bethcryer requested changes

2023-01-26 13:56 UTC, bethcryer commented on .github/workflows/deploy.yml
> +        uses: aws-actions/amazon-ecs-deploy-task-definition@de0132cf8cdedb79975c6d42b77eb7ea193cf28e
Think this can be `aws-actions/amazon-ecs-deploy-task-definition@v1`

2023-01-26 13:56 UTC, bethcryer commented on .github/workflows/deploy.yml
> +
Add the `Download task definition` stage I sent to you on slack

2023-01-26 13:56 UTC, bethcryer commented on .github/workflows/deploy.yml
> +
We probably also want to include the `Fill in the new image ID in the Amazon ECS task definition` stage from the github documentation example of this: [link](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service)  

We can then use the image ID to rollback to a previous image in the ECS if we need to

2023-01-26 13:56 UTC, bethcryer commented on .github/workflows/deploy.yml
> +    ECS_TASK_DEFINITION: .aws/task-definition.json
This can just be `task-definition.json` now

2023-01-26 13:56 UTC, bethcryer commented on .github/workflows/deploy.yml
> +          registry: ${{ env.REGISTRY }}
You need to copy the environment variables from `docker-build.yml` into this action's `env:` section

2023-01-26 13:56 UTC, bethcryer commented on .github/workflows/deploy.yml
> +          registry: ${{ env.REGISTRY }}
Should also delete` docker-build.yml` if we're replacing it with this

2023-01-27 13:43 UTC, bethcryer requested changes

2023-01-27 13:43 UTC, bethcryer commented on .github/workflows/deploy.yml
> +            aws ecs describe-task-definition --task-definition answerking-dotnet-api-task --query taskDefinition > task-definition.json
Can swap out `task-definition.json` for `${{ env.ECS_TASK_DEFINITION }}`

2023-01-27 13:43 UTC, bethcryer commented on .github/workflows/deploy.yml
> +        uses: actions/checkout@v3
Remove this bit I've highlighted - this is the job definition section copied from the old docker yml, but in this yml we already define the job earlier and ran the checkout action.

2023-01-27 13:43 UTC, bethcryer commented on .github/workflows/deploy.yml
> +          image: ${{ steps.build-image.outputs.image }}
This needs to be `steps.build-image.outputs.imageid`

2023-01-27 16:38 UTC, bethcryer commented on .github/workflows/deploy.yml
> +        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
Missed this, should also be @v1

2023-01-30 09:45 UTC, CallumMcGregorAD commented on .github/workflows/deploy.yml
> +        uses: aws-actions/configure-aws-credentials@13d241b293754004c80624b5567555c4a39ffbe3
Thought I'd got them all, changed now

2023-01-30 12:01 UTC, bethcryer approved these changes, later dismissed

2023-02-01 09:55 UTC, DWatson1993 submitted a review, later dismissed

2023-02-01 11:40 UTC, bethcryer approved these changes

2023-02-01 11:45 UTC, DWatson1993 approved these changes

2023-02-01 11:48 UTC, merged