BENCH 106: Create Docker Image for Answer King C# app
AnswerConsulting/AnswerKing-CS pull request #8
Opened 2022-11-04 14:43 UTC by mbaltrimas

adds an action that builds a docker image every time a push is made to `main` or `develop`

currently doesn't push the image anywhere as its a separate ticket

2022-11-04 14:57 UTC, milkshakeuk requested changes
Just the one change for now 😊

2022-11-04 14:57 UTC, milkshakeuk commented on dockerfile
> +# syntax=docker/dockerfile:1
this docker file will re-build the binaries which might have already been built as part of other actions... not necessarily an issue but something that could be optimised later.

2022-11-04 14:57 UTC, milkshakeuk commented on .github/workflows/build.yml
> +# Workflow for building a docker image
we should probably rename this file to `docker-build.yml` for now.

2022-11-04 14:57 UTC, milkshakeuk commented on .github/workflows/build.yml
> +    branches:
do we want to do this on every push to `main` and `develop` ? I guess it's fine for now but something to think about and maybe discuss.

2022-11-07 10:24 UTC, milkshakeuk approved these changes
Looks good!

2022-11-07 10:46 UTC, harrystead2 approved these changes

2022-11-07 10:50 UTC, merged