Bench 309
AnswerConsulting/AnswerKing-CS pull request #83
Opened 2023-02-01 18:00 UTC by khayamAmin

2023-02-06 10:19 UTC, bethcryer requested changes

2023-02-06 10:19 UTC, bethcryer commented on src/Answer.King.Api/appsettings.json
> +    "AnswerKing": "filename=Answer.King.db;"
This was changed from `db/Answer.King.db` by BENCH-305, I think you reverted it in your rebase so could you please change this connection string back to that?

2023-02-06 10:19 UTC, bethcryer commented on src/Answer.King.Api/appsettings.Development.json
> +    "AnswerKing": "filename=Answer.King.db;"
also needs to be `db/Answer.King.db`

2023-02-06 11:55 UTC, bethcryer submitted a review, later dismissed

2023-02-06 15:13 UTC, harrystead2 approved these changes, later dismissed

2023-02-06 15:42 UTC, milkshakeuk commented on src/Answer.King.Domain/Answer.King.Domain.csproj
> +    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="3.7.104.4" />
wow this doesn't seem right! domain should not reference serilog.

2023-02-06 15:43 UTC, milkshakeuk commented on src/Answer.King.Infrastructure/Answer.King.Infrastructure.csproj
> +    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="3.7.104.4" />
pretty sure these are not needed here.

2023-02-06 15:45 UTC, milkshakeuk commented on src/Answer.King.Api/GlobalSuppressions.cs
> +[assembly: SuppressMessage("Performance", "CA1848:Use the LoggerMessage delegates", Justification = "Performance improvement is minor", Scope = "member", Target = "~M:Answer.King.Api.Controllers.Paym
are these supressions needed?

2023-02-08 09:19 UTC, bethcryer commented on .gitignore
> +/src/Answer.King.Api/appsettings.Production.json
Did you mean to exclude the production appsettings? It's still being tracked in git here

2023-02-08 09:55 UTC, bethcryer approved these changes

2023-02-08 15:46 UTC, harrystead2 approved these changes

2023-02-08 16:08 UTC, merged