Bench 357
AnswerConsulting/AnswerKing-CS pull request #87
Opened 2023-02-07 12:07 UTC by FoxHawk

Added checks for duplicate names for Products, Categories, and Tags. The POST & PUT endpoints now return 409 conflict errors if there are any name conflicts

2023-02-08 09:15 UTC, bethcryer requested changes
Only one change needed in the current code, but you'll also have to write tests to cover the new name-conflict conditions before the Sonarcloud check will pass.

2023-02-08 09:15 UTC, bethcryer commented on src/Answer.King.Api/Controllers/CategoriesController.cs
> +            return this.Conflict();
I don't think we should be using 409 Conflict for this, that's more for when there's a conflict between request and server state.

Could you change these to a 400 Bad Request?

2023-02-09 11:26 UTC, bethcryer approved these changes

2023-02-09 13:30 UTC, CallumMcGregorAD approved these changes

2023-02-09 13:57 UTC, merged