BENCH-354
AnswerConsulting/AnswerKing-CS pull request #88
Opened 2023-02-08 15:00 UTC by CallumMcGregorAD

fixed api bugs and logic errors

2023-02-08 16:07 UTC, bethcryer requested changes
Left a couple comments, but also noticed something else I think needs doing:

In CreateCategory, we need to ensure that for any product(s) added to the category during the create request, it is also removed from its old category the same way we're now doing in UpdateCategory.

2023-02-08 16:07 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +        var category = categories.FirstOrDefault(x => x.Id == categoryId);
is there a reason this was changed from `var category = await this.Categories.GetOne(categoryId);`?

2023-02-08 16:07 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +        var updatedCategories = new List<long>
this variable isn't being used

2023-02-08 16:07 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
>          }
I don't think this needs to be here anymore

2023-02-08 16:08 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
>          }
if you delete this, then you can also safely remove the `oldProducts` variable

2023-02-09 13:26 UTC, CallumMcGregorAD commented on src/Answer.King.Api/Services/CategoryService.cs
> +        var category = categories.FirstOrDefault(x => x.Id == categoryId);
changed back and refactored

2023-02-09 13:27 UTC, CallumMcGregorAD commented on src/Answer.King.Api/Services/CategoryService.cs
>          }
This removes existing products from the new products check list as they don't change. Have refactored too

2023-02-09 15:51 UTC, bethcryer requested changes

2023-02-09 15:51 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +        await this.Categories.Save(category);
I don't think you should save the category here, only after all the products have been added - if there's an error during the rest of the function, it shouldn't create the category.

2023-02-09 15:51 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +            }
did you forget to remove this block? you're doing the same thing again on the next line with `RemoveFromCategory`

2023-02-09 15:51 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +    private async Task RemoveFromCategory(Product product)
Could you rename to `RemoveProductFromCategory`

2023-02-09 17:11 UTC, bethcryer approved these changes

2023-02-10 09:40 UTC, zoe-salmon-answer commented on src/Answer.King.Api/Services/CategoryService.cs
> +        foreach (var updateId in newProducts)
Since we're only iterating over the `newProducts` to add here, do we not allow removing a product from a category as part of this method (by design)?

2023-02-10 09:45 UTC, zoe-salmon-answer approved these changes
Just a small question in the previous comment, the rest looks good!

2023-02-10 09:59 UTC, bethcryer commented on src/Answer.King.Api/Services/CategoryService.cs
> +        foreach (var updateId in newProducts)
We didn't want to allow a product to exist without a category, and removing the category from the product here would cause that. So we had to remove that functionality from this endpoint and force the end-user to either use the product's endpoint to edit its category or remove it from a category by adding it to another category via its endpoint.

2023-02-10 10:04 UTC, zoe-salmon-answer commented on src/Answer.King.Api/Services/CategoryService.cs
> +        foreach (var updateId in newProducts)
Gotcha, makes sense!

2023-02-10 10:06 UTC, merged