BENCH-395: Refactor Tags endpoints
AnswerConsulting/AnswerKing-CS pull request #89
Opened 2023-02-13 13:48 UTC by zoe-salmon-answer

Improving the match on the shared specification
Removed GET `tags/{id}/products` endpoint (required productIds on `tags` and `tags/{id}` endpoints already present)
Merged other `tags/{id}/products` endpoints into PUT `tags/{id}`
Updated tests to match new structure, verifying more exceptional cases

2023-02-14 10:00 UTC, bethcryer requested changes

2023-02-14 10:00 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
>          await this.Tags.Save(tag);
Could we move this `Save` and the one in `AssociateTagAndProducts` to the end of the function? I don't think it should half-create the Tag in the case of an error, we ought to do the error checks and then save once we know the request has been fully valid.

2023-02-14 10:00 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
>              await this.Products.AddOrUpdate(product);
think you'll have to move this into a second loop over `products` that runs after all of the possible exception points have been passed successfully

2023-02-14 10:00 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
> +            await this.Products.AddOrUpdate(product);
Again, I think we should refactor so that nothing is saved until after this and the `AssociateTagAndProducts` method have run successfully

2023-02-14 10:48 UTC, zoe-salmon-answer commented on src/Answer.King.Api/Services/TagService.cs
>          await this.Tags.Save(tag);
The issue I was having with this is the ID isn't created on the tag until it's saved, which is required for the `product.AddTag(new TagId(tag.Id));` association... 😅

I could look into adding a transaction around this if we're wanting to make sure the data integrity is upheld?

2023-02-14 11:01 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
> +        var tag = new Tag(
it seems like you're adding the products to the tag here and then doing it again in the association method? I think this should just make a new list, and then we add the products one by one as we check that they exist

2023-02-14 11:10 UTC, zoe-salmon-answer commented on src/Answer.King.Api/Services/TagService.cs
> +        var tag = new Tag(
Yeah, that's fair, adding them here is effectively a duplicate. 👍

2023-02-14 11:14 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
>          await this.Tags.Save(tag);
Ahh gotcha, ok yea probably just leave it then unless you can come up with a neat solution for that

2023-02-14 11:57 UTC, zoe-salmon-answer commented on src/Answer.King.Api/Services/TagService.cs
>          await this.Tags.Save(tag);
I've added a base repository and methods to start, commit and rollback transactions to achieve this, along with a test to verify that we're not getting a partial addition.

2023-02-14 15:12 UTC, bethcryer approved these changes, later dismissed

2023-02-15 10:26 UTC, khayamAmin approved these changes, later dismissed

2023-02-15 11:17 UTC, bethcryer approved these changes

2023-02-15 15:12 UTC, harrystead2 approved these changes

2023-02-15 15:13 UTC, merged