Removed Problematic Errors From Product Class
AnswerConsulting/AnswerKing-CS pull request #98
Opened 2023-02-16 16:37 UTC by hazel-davis

Currently for any tags with retired products, you cannot edit this tag via a `tags/id` `put` request. If you leave the retired tag in you get a "_Cannot add tag to retired product_" error and if you leave it out you get a ''_Cannot remove tag from retired product_." error.

2023-02-17 09:27 UTC, bethcryer requested changes

2023-02-17 09:27 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
> +        var tagProductIdsToRemove = tag.Products.Where(x => !updateTag.Products.Contains(x.Value));
I don't think this needs changing, ProductId has an implicit conversion operator so it should use the Value automatically

2023-02-17 09:27 UTC, bethcryer commented on src/Answer.King.Api/Services/TagService.cs
> +            var alreadyAssociated = tag.Products.FirstOrDefault(tagProduct => tagProduct.Value == productId) != null;
Do you think you could add this to the other services too if it's a recurring problem?

2023-02-17 09:34 UTC, hazel-davis commented on src/Answer.King.Api/Services/TagService.cs
> +            var alreadyAssociated = tag.Products.FirstOrDefault(tagProduct => tagProduct.Value == productId) != null;
I don't believe the other services have this problem, I'll double check

2023-02-17 12:51 UTC, bethcryer approved these changes, later dismissed

2023-02-17 12:52 UTC, FoxHawk submitted a review, later dismissed

2023-02-17 14:27 UTC, bethcryer approved these changes, later dismissed

2023-02-17 15:22 UTC, zoe-salmon-answer approved these changes

2023-02-20 12:20 UTC, beth-cryer approved these changes

2023-02-20 13:15 UTC, bethcryer approved these changes

2023-02-20 13:16 UTC, merged